-- HAILE HOTEL SODO — REAL DATABASE SETUP
-- Run this in Supabase SQL Editor.
-- After creating the manager account, disable public sign-ups in:
-- Authentication -> Providers -> Email -> Allow new users = OFF.

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric(12,2) not null default 0,
  description text default '',
  ingredients jsonb not null default '[]'::jsonb,
  nutrition jsonb not null default '{}'::jsonb,
  image text default 'chicken',
  created_at timestamptz not null default now()
);

alter table public.menu_items enable row level security;

-- Customers can read the menu without logging in.
drop policy if exists "Public can read menu" on public.menu_items;
create policy "Public can read menu"
on public.menu_items for select
to anon, authenticated
using (true);

-- Only authenticated manager accounts can change the menu.
drop policy if exists "Managers can insert menu" on public.menu_items;
create policy "Managers can insert menu"
on public.menu_items for insert
to authenticated
with check (true);

drop policy if exists "Managers can update menu" on public.menu_items;
create policy "Managers can update menu"
on public.menu_items for update
to authenticated
using (true)
with check (true);

drop policy if exists "Managers can delete menu" on public.menu_items;
create policy "Managers can delete menu"
on public.menu_items for delete
to authenticated
using (true);

-- OPTIONAL SAMPLE ITEM (use only if you want a test item):
-- insert into public.menu_items (name, category, price, description, ingredients, nutrition, image)
-- values ('Test Chicken Sandwich', 'Sandwich', 400, 'TEST ITEM — replace with real hotel data.',
-- '["Chicken", "Bread", "Lettuce"]'::jsonb,
-- '{"calories":"—","protein":"—","carbs":"—","fat":"—","fiber":"—","vitamins":"—"}'::jsonb,
-- 'chicken');
